/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://gyr5p5wtlzhr3k3f5nhoq6kah4.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-afxmybcdjbgx7ev5h5qxjif7xm",
    "aws_cognito_identity_pool_id": "ap-south-1:539be99a-5310-4c0d-a08b-83d2de0a9a6a",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_FhEtgvlbQ",
    "aws_user_pools_web_client_id": "5nnbm3qp6pchhvfhu1b3e0q5o7",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
